# Generated by Django 6.0.6 on 2026-06-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='pincode',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
